### ISSUE TITLE
When using keys to scroll the beginning of animation is jumpy

### ISSUE THREAD

**Issue by adamhughes86** [lukehaas/Scrollify#105]
When using the keys to navigate the sections the beginning of the animation seems to stutter. This is not happening on other navigation methods. Seems to be a bit temperamental but I've seen it on my own site and also the demo site. Can be quite hard to see the the default easing. I only noticed it because I needed an easing which was slowing at the start and finished quickly.

----
Device Details:
Macintosh OS X 10.11.4
Chrome 50.0.2661.94
Browser size 2560 x 1253

**Comment by lukehaas** [comment]
This is unfortunately a known Scrollify issue. It's due to Scrollify needing to check whether it can let you scroll normally with the keys or if it should snap to the next section. In the case of a very long section it would need to let you scroll normally. So what you're seeing is a brief moment of normal scrolling while Scrollify works this out. 
I'm not sure if there's a good solution for this, but if I ever think of one I'll be sure to push an update.

**Comment by adamhughes86** [comment]
Ah I can see how that would be an issue.

Is there a way to turn of the keyboard navigation through the options?

**Comment by lukehaas** [comment]
No, there's no option to disable the keyboard navigation.

**Comment by lukehaas** [comment]
This has been improved with the latest version of Scrollify.
