### ISSUE TITLE
Update() doesn't work normally if called after resize with setHeights set to false

### ISSUE THREAD

**Issue by vk011** [lukehaas/Scrollify#111]
I have `setHeights`set to false as I am calculating heights myself. It works fine on page load, but after resize in the plugin options I call the `update()` function and the sections starts adjusting extremely slowly.

Actually it's the same even if `setHeight` is set to true, if you call `update()` in the `afterResize` callback it's extremely slow.

**Comment by lukehaas** [comment]
Thanks, I'll look into this.

**Comment by lukehaas** [comment]
I've pushed an update that resolves this.
Calling `update()` in `afterResize()` should still be avoided though as Scrollify updates itself automatically when the page is resized. Calling `update()` will just run the same code again.

`update()` is intended for scenarios where a section's height has changed due to a change in content etc.
