### ISSUE TITLE
Controlling the "weight" or stickiness of the scroll

### ISSUE THREAD

**Issue by bshoults** [lukehaas/Scrollify#270]
Not quite how to phrase the question... By default, any vertical scrolling triggers the next section. Is it possible to adjust this to make it a bit stickier. Something like 20px triggers the next section? Sorry if this has been asked.

**Comment by lukehaas** [comment]
Have you thought about the UX implications of this? Might not be good for the user if the page doesn't react to their scrolling.

**Comment by bshoults** [comment]
OK, fair point, though with the current implementation, any twitch can trigger the scroll (especially on a trackpad), which might be frustrating for the user. 20px is probably too drastic of a change. Maybe something as small as 4-5px might do the trick.

**Comment by tiymfony** [comment]
i beleive the implementation you're thinking of @bshoults would be if instead of sticky scroll, the element that takes up the most area of the container became sticky after a small millisecond interval of a released scroll or maybe even if you could choose for it to autoscroll to next element after said interval
