### ISSUE TITLE
Scrollify on mobile devices

### ISSUE THREAD

**Issue by davidinhowas** [lukehaas/Scrollify#31]
Hello! I have a question. How can i disable this JavaScript plugin on mobill phpnes and tablets? I will be very grateful if you'll give me the answer!!

**Comment by lukehaas** [comment]
Hi, That could be a little tough because the idea of desktops, phones, and tablets as distinct things is disappearing. A desktop can be small and could also potentially have a touch screen, similarly a tablet could be used with a keyboard and mouse.
Scrollify works well on all screen sizes and works well with touch too, so the ideal would be not to disable it. However if you really need to then I'd say create a condition that checks the size of the page and whether touch is available and base the initialisation of Scrollify on this.

**Comment by davidinhowas** [comment]
Thanks a lot!

**Comment by davidinhowas** [comment]
I can say I need that.

**Comment by chuckarte** [comment]
Hi, I'm having some overflow scroll issues with Scrollify.
When a section is larger than 100% and I try to scroll in my iPhone scroll gets stuck and it doesnt respond until I lift my finger, is there a workaround for this?

**Comment by lukehaas** [comment]
Hi,
In the scenario you are describing Scrollify will scroll you to the bottom of the section without you needing to lift your finger. Scrollify just needs to register that your intention is to scroll which is based on how far your finger has moved and for how long
