### ISSUE TITLE
Problem with Chrome

### ISSUE THREAD

**Issue by mushi93** [lukehaas/Scrollify#78]
Hi, im having a problem with chrome browser, it just wont scroll. It works perfectly on safari and firefox tho.

What could be the issue?

thank you

**Comment by beyoyo2** [comment]
Having same problem. Only chrome.
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///Volumes/xxx/xxx/data/index.html#section-0' cannot be created in a document with origin 'null'.

**Comment by pnwnelson** [comment]
I have this same error but when I deploy and don't use local paths, it's fine.

**Comment by lukehaas** [comment]
For security reasons Chrome won't let you push states to the history object when running a page from your file system. This relates to the hash value Scrollify puts at the end of the URL when you scroll to different sections. 
I'd recommend setting up a local server and doing your dev work there.

In the meantime I'll update Scrollify in my next batch of updates so that this error is caught gracefully rather than breaking the whole page. However, the functionality at the centre of this issue will still only work on a hosted page.

**Comment by mushi93** [comment]
thank you very much Luke!
