### ISSUE TITLE
Conflict with vertical nav bar?

### ISSUE THREAD

**Issue by pnwnelson** [lukehaas/Scrollify#84]
Howdy. Excellent work on this! I'm experiencing an issue though; when using my vertical navbar and I click on the "home" button (the top section) when I'm in section #3, it seems to disable the mouse scroll down action... until I scroll up. If I only use the mouse to scroll, it works great. If I go back and forth with mouse scroll and navbar scroll, there seems to be this issue. If you need a visual, go to pnwnelson.com, using the mouse scroll, then use the navbar to go from the #3 section to the #1 section, then try mouse scroll again. It does it in Chrome and Safari. Thanks for any time in looking at this.

**Comment by lukehaas** [comment]
The problem is your `smoothScroll` function. You'll need to use Scrollify's `move` method in place of this for things to work properly.

**Comment by pnwnelson** [comment]
Thanks for the response. I disconnected the other js file with the `smoothScroll` completely and I'm still experiencing the issue. Maybe a conflict with modernizr.js? I know the issue doesn't exist (that I've found) on a touch device. So something in one of the mouse handlers?

**Comment by lukehaas** [comment]
This is the same issue as before. The whole issue is down to the page being scrolled outside of Scrollify. Scrollify still thinks you're on the previous panel.
Previously it was due to the `smoothScroll` function, without that, I see you have IDs on you panels that match the hash values. This means the page will anchor to those sections when the nav links are clicked. So still a case of the page being scrolled outside of Scrollify.
To amend this you need to use `sectionName` remove those IDs and put them in the `sectionName` data-attribute, and use the `move` method to scroll the page when the nav links are clicked.

**Comment by pnwnelson** [comment]
Ok. I appreciate you taking the time for the explanation.
